# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod properties
mod.name=SwordBlocking
mod.id=swordblocking
mod.version=1.0
mod.group=eu.midnightdust.swordblocking
mod.description=Adds sword blocking to new versions, you just need a shield in your offhand (or ViaVersion)!
mod.source=https://github.com/TeamMidnightDust/SwordBlocking
mod.issues=https://github.com/TeamMidnightDust/SwordBlocking/issues
mod.license=MIT
mod.modrinth=https://modrinth.com/mod/sword-blocking
mod.curseforge=http://curseforge.com/minecraft/mc-mods/sword-blocking
mod.discord=https://discord.gg/jAGnWYHm3r

# Publishing
publish.modrinth=
publish.curseforge=

# Dependencies
deps.fabric_loader_version=0.17.3
deps.midnightlib_version=1.9.1

deps.devauth_version=1.2.1
deps.lombok_version=1.18.42
deps.mixinconstraints_version=1.1.0
deps.mixinsquared_version=0.2.0

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_dep=[VERSIONED]
mod.mc_version=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]
deps.neoforge_version=[VERSIONED]
